### PR TITLE
[Controls] Tweaks to Interaction Bar & Leave App Button Positions

### PR DESCRIPTION
**Pull request by cleeuh**
- Memoized Lasso and Whiteboard

- Swapped grab and pointer interaction positions
image

- Hamburger menu
image

### CODE REVIEW

**Comment by rctheriot** [comment]
Maybe its time we move all the buttons besides the delete app into a hamburger menu

**Comment by cleeuh** [comment]
> Maybe its time we move all the buttons besides the delete app into a hamburger menu

@rctheriot Sounds good, will do.

**Comment by rctheriot** [comment]
> > Maybe its time we move all the buttons besides the delete app into a hamburger menu
> 
> @rctheriot Sounds good, will do.

I would make the Hamburger menu gray and the trashcan delete a red button.

**Comment by cleeuh** [comment]
Would this be the preferred ordering?

image

**Comment by rctheriot** [comment]
Looks good! Maybe change the "Pin" icon to  `MdPushPin`

**Comment by cleeuh** [comment]
image

**Pull request merged**
